/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface xhettesAmbulanceWlList {
    }
}
declare global {
    interface HTMLxhettesAmbulanceWlListElement extends Components.xhettesAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLxhettesAmbulanceWlListElement: {
        prototype: HTMLxhettesAmbulanceWlListElement;
        new (): HTMLxhettesAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xhettes-ambulance-wl-list": HTMLxhettesAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface xhettesAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xhettes-ambulance-wl-list": xhettesAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xhettes-ambulance-wl-list": LocalJSX.xhettesAmbulanceWlList & JSXBase.HTMLAttributes<HTMLxhettesAmbulanceWlListElement>;
        }
    }
}
